CREATE DATABASE IF NOT EXISTS beyond_db;
USE beyond_db;

-- SET time_zone = 'America/São_Paulo';


CREATE TABLE IF NOT EXISTS TB_ENDERECO (
  ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
  PAIS VARCHAR(45),
  ESTADO VARCHAR(45),
  CIDADE VARCHAR(45),
  RUA VARCHAR(255),
  NUMERO_RUA INT,
  COMPLEMENTO VARCHAR(45),
  CEP CHAR(10)
);

CREATE TABLE IF NOT EXISTS TB_EMPRESA (
  ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(45),
  CNPJ CHAR(15),
  CHAVE_ATIVACAO CHAR(15),
  EMAIL VARCHAR(45),
  TEL CHAR(14),
  FRANQUIA VARCHAR(45)
);

INSERT INTO TB_EMPRESA VALUES(default, "beyond", "0001129938-99", 123456, "beyond@gg","11946776601","Matriz"); 
USE beyond_db;
CREATE TABLE IF NOT EXISTS TB_ENDERECO_EMPRESA (
  ID_END_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,
  FK_ENDERECO INT,
  FK_EMPRESA INT,
  TIPO VARCHAR(45),
  FOREIGN KEY (FK_ENDERECO) REFERENCES TB_ENDERECO(ID_ENDERECO),
  FOREIGN KEY (FK_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIO (
  ID_FUNC INT PRIMARY KEY AUTO_INCREMENT,
  FK_EMPRESA INT,
  NOME VARCHAR(45),
  CPF CHAR(11),
  EMAIL VARCHAR(45),
  TEL CHAR(14),
  SENHA VARCHAR(45),
  TIPO VARCHAR(45),
  CARGO VARCHAR(45),
  FOTO VARCHAR(200),
  FOREIGN KEY (FK_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE IF NOT EXISTS TB_ANOTACOES (
  ID_ANOTACOES INT PRIMARY KEY AUTO_INCREMENT,
  FK_FUNC INT,
  FK_EMPRESA INT,
  TITULO VARCHAR(45),
  DESCRICAO VARCHAR(200),
  DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
  COR CHAR(6),
  FOREIGN KEY (FK_FUNC) REFERENCES TB_FUNCIONARIO(ID_FUNC),
  FOREIGN KEY (FK_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE IF NOT EXISTS TB_LOG (
  ID_LOG INT PRIMARY KEY AUTO_INCREMENT,
  FK_FUNC INT,
  FK_EMPRESA INT,
  CATEGORIA VARCHAR(45),
  DESCRICAO VARCHAR(200),
  DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (FK_FUNC) REFERENCES TB_FUNCIONARIO(ID_FUNC),
  FOREIGN KEY (FK_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE IF NOT EXISTS TB_EVENTOS (
  ID_EVENTOS INT PRIMARY KEY AUTO_INCREMENT,
  FK_EMPRESA INT,
  NOME VARCHAR(45),
  DATA_INICIO DATE,
  DATA_TERMINO DATE,
  DESCRICAO VARCHAR(200),
  COR CHAR(7),
  FOREIGN KEY (FK_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);


CREATE TABLE IF NOT EXISTS TB_FILTRO_DASHBOARD (
  ID_FILTRO INT PRIMARY KEY AUTO_INCREMENT,
  FK_EMPRESA INT,
  NOME VARCHAR(45),	
  DATA_CHEGADA DATE,
  FK_CONTINENTE INT,
  FK_PAIS INT,
  FK_VIA INT,
  FK_FEDERACAO_BRASIL INT,
  FOREIGN KEY (FK_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE IF NOT EXISTS TB_NOTIFICACAO (
  ID_NOTIFICACAO INT PRIMARY KEY AUTO_INCREMENT,
  FK_EMPRESA INT,
  TITULO VARCHAR(45),
  DESCRICAO VARCHAR(200),
  STATUS_NOTIFICACAO VARCHAR(45),
  FOREIGN KEY (FK_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE IF NOT EXISTS TB_ETL_LOG (
  ID_ETL_LOG INT PRIMARY KEY AUTO_INCREMENT,
  TIPO_LOG VARCHAR(80),
  DESCRICAO VARCHAR(256),
  DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS CONTINENTE (
    ID_CONTINENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45)
);




CREATE TABLE IF NOT EXISTS FEDERACAO_BRASIL (
    ID_FEDERACAO_BRASIL INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45)
);


CREATE TABLE IF NOT EXISTS VIA (
    ID_VIA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_VIA VARCHAR(45)
);


CREATE TABLE IF NOT EXISTS PAIS (
    ID_PAIS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PAIS VARCHAR(45),
    FK_CONTINENTE INT,
    FOREIGN KEY (FK_CONTINENTE) REFERENCES CONTINENTE(ID_CONTINENTE)
);


CREATE TABLE IF NOT EXISTS TB_BASE_DADOS (
    ID_BASE_DADOS INT PRIMARY KEY AUTO_INCREMENT,
    DATA_CHEGADA DATE,
    CHEGADAS INT,
    FK_VIA INT,
    FK_PAIS INT,
    FK_CONTINENTE INT,
    FK_FEDERACAO_BRASIL INT,
    FOREIGN KEY (FK_VIA) REFERENCES VIA(ID_VIA),
    FOREIGN KEY (FK_PAIS) REFERENCES PAIS(ID_PAIS),
    FOREIGN KEY (FK_CONTINENTE) REFERENCES CONTINENTE(ID_CONTINENTE),
    FOREIGN KEY (FK_FEDERACAO_BRASIL) REFERENCES FEDERACAO_BRASIL(ID_FEDERACAO_BRASIL)
);


SELECT * FROM TB_BASE_DADOS;
SELECT * FROM TB_FUNCIONARIO WHERE ID_FUNC = 1;
DESC TB_FUNCIONARIO;
USE beyond_db;














